ДЗ 1
ElonMax/2020-2-Atom-QA-Python-M-Skorokhodov pull request #1
Opened 2020-09-28 19:14 UTC by ElonMax

# Домашнее задание №1

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
Написано по 5 автотестов на 5 структур данных: int, list, dict, str, set

2020-10-05 11:56 UTC, snicks92 requested changes
Хорошая работа, маленький коммент оставил

2020-10-05 11:56 UTC, snicks92 commented on hw1/tests/test_dictionary.py
> +        assert dict_num.clear() is None
Yе сказал бы что тут проверяется то что указано в комментах. Cейчас проверяется только что метод clear  возвращает None. А надо бы проверить что словарь действительно стал пустым

2020-10-07 21:38 UTC, ElonMax commented
Исправил ошибки

2020-10-08 00:29 UTC, snicks92 approved these changes

2020-10-08 00:29 UTC, snicks92 commented
Теперь хорошо, спасибо

2020-10-08 00:29 UTC, merged